<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_search</name>
   <tag></tag>
   <elementGuidId>45809bc2-7a68-43c0-ae84-77685b2ae06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tsf&quot;]/div[2]/div[1]/div[2]/div[2]/div[2]/center/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tsf&quot;]/div[2]/div[1]/div[2]/div[2]/div[2]/center/input[1]</value>
   </webElementProperties>
</WebElementEntity>
